package com.agentrelay

import android.content.Context
import android.util.Log
import org.json.JSONObject

/**
 * Persistently caches LLM-generated app capability descriptions.
 * Maps package name → 1-line description of what the app can do.
 * Descriptions are generated by the planning LLM on first task run
 * and reused across all future sessions.
 */
object AppKnowledgeCache {

    private const val TAG = "AppKnowledgeCache"
    private const val PREFS_NAME = "app_knowledge_cache"
    private const val KEY_DESCRIPTIONS = "descriptions_json"

    @Volatile
    private var descriptions: MutableMap<String, String> = mutableMapOf()

    @Volatile
    private var loaded = false

    fun getDescription(packageName: String): String? = descriptions[packageName]

    fun getMissingApps(allApps: List<AppInfo>): List<AppInfo> {
        return allApps.filter { !descriptions.containsKey(it.packageName) }
    }

    fun saveDescriptions(newDescriptions: Map<String, String>, context: Context) {
        descriptions.putAll(newDescriptions)
        persistToPrefs(context)
        Log.d(TAG, "Saved ${newDescriptions.size} app descriptions (total: ${descriptions.size})")
    }

    fun loadDescriptions(context: Context) {
        if (loaded) return
        try {
            val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            val json = prefs.getString(KEY_DESCRIPTIONS, null)
            if (json != null) {
                val jsonObj = JSONObject(json)
                val map = mutableMapOf<String, String>()
                for (key in jsonObj.keys()) {
                    map[key] = jsonObj.getString(key)
                }
                descriptions = map
                Log.d(TAG, "Loaded ${map.size} cached app descriptions")
            }
        } catch (e: Exception) {
            Log.w(TAG, "Failed to load app knowledge cache", e)
        }
        loaded = true
    }

    private fun persistToPrefs(context: Context) {
        try {
            val jsonObj = JSONObject()
            descriptions.forEach { (pkg, desc) -> jsonObj.put(pkg, desc) }
            val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
            prefs.edit().putString(KEY_DESCRIPTIONS, jsonObj.toString()).apply()
        } catch (e: Exception) {
            Log.w(TAG, "Failed to persist app knowledge cache", e)
        }
    }
}
